spring:
  application:
    name: boot-admin
  profiles:
    active: dev
  # ???????
  datasource:
    # ??????? jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ????
    url: jdbc:mysql://localhost:3306/boot-admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # ???
    username: root
    # ??
    password: 123456

# ??
server:
  # spring boot ???? 8080
  port: 9000

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # ??????????? controller
      packages-to-scan: com.chuxin.bootadmin.controller

# knife4j???????????????
knife4j:
  enable: true
  # ????????
  # production: true
  setting:
    language: zh_cn

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: if_delete
      logic-delete-value: 1
      logic-not-delete-value: 0